name: build
on:
  workflow_dispatch:
  push:
    tags:
      - '*-ponces.*'
env:
  RUST_BACKTRACE: 1
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - run: sudo apt-get install libdbus-1-dev pkg-config
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: |
          cargo build --release
          cd target/release
          tar -czf bitchat_${{ github.ref_name }}_linux_amd64.tar.gz bitchat
      - uses: softprops/action-gh-release@v2.2.1
        with:
          files: target/release/bitchat_${{ github.ref_name }}_linux_amd64.tar.gz
  #build-musl:
  #  runs-on: ubuntu-latest
  #  permissions:
  #    contents: write
  #  steps:
  #    - run: sudo apt-get install clang-18 libdbus-1-dev pkg-config
  #    - uses: actions/checkout@v3
  #    - uses: dtolnay/rust-toolchain@stable
  #      with:
  #        targets: x86_64-unknown-linux-musl
  #    - run: |
  #        TARGET_CC=clang-18 TARGET_AR=llvm-ar-18 cargo build --target x86_64-unknown-linux-musl --release
  #        cd target/x86_64-unknown-linux-musl/release
  #        tar -czf bitchat_${{ github.ref_name }}_linux-musl_amd64.tar.gz bitchat
  #    - uses: softprops/action-gh-release@v2.2.1
  #      with:
  #        files: target/x86_64-unknown-linux-musl/release/bitchat_${{ github.ref_name }}_linux-musl_amd64.tar.gz
  build-macos:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: |
          cargo build --release
          cd target/release
          tar -czf bitchat_${{ github.ref_name }}_macOS_amd64.tar.gz bitchat
      - uses: softprops/action-gh-release@v2.2.1
        with:
          files: target/release/bitchat_${{ github.ref_name }}_macOS_amd64.tar.gz
  build-android:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: |
          cargo install cross --git https://github.com/cross-rs/cross
          cross build --target aarch64-linux-android --release
          cd target/aarch64-linux-android/release
          tar -czf bitchat_${{ github.ref_name }}_linux-android_arm64.tar.gz bitchat
      - uses: softprops/action-gh-release@v2.2.1
        with:
          files: target/aarch64-linux-android/release/bitchat_${{ github.ref_name }}_linux-android_arm64.tar.gz
